(->> (f-read-text "example-input.txt")
   (s-trim)
   (s-lines)
   (-map #'s-collapse-whitespace)
   (-map #'s-split-words)
   ;; (-map #'string-to-number)
   (--map (list (string-to-number (car it))
               (string-to-number (cadr it))))
   (-unzip)
   (--map (-sort #'< it))
   (-reduce (-partial #'-zip-with #'-))
   (-map #'abs)
   (-sum)
   )

;; (-map #'string-to-number (list "3" "4"))
