(->> (f-read-text "example-input.txt")
   (s-trim)
   (s-lines)
   (-map #'s-split-words)
   (-map (-partial #'-map #'string-to-number))
   (-unzip)
   (--map (-sort #'< it))
   (apply #'-zip-with #'-)
   (-map #'abs)
   (-sum)
   )
